Creating test_utils.py
IMMM-SFA/msd_uncertainty_ebook pull request #113
Opened 2024-08-20 18:59 UTC by Jaydon2005

Provides a DataFrame with random values for logistic regression testing. Ensures that a scatter plot has been added by checking the number of collections in the axis. Makes sure that the axis limits and labels are set correctly

2025-01-08 17:43 UTC, erexer requested changes
Double check that you have pre-commit running, my comp said that two files were reformatted by the black hook.

2025-01-08 17:43 UTC, erexer commented on msdbook/tests/test_utils.py
> +    predictors = ['Predictor1', 'Predictor2']
you should define this in `sample_data()`

2025-01-08 17:43 UTC, erexer commented on msdbook/tests/test_utils.py
> +import pytest
make sure pytest is listed in the requirements, [like on the main branch](https://github.com/IMMM-SFA/msd_uncertainty_ebook/blob/main/pyproject.toml#L66)

2025-01-08 17:43 UTC, erexer commented on msdbook/tests/test_utils.py
> +        ax, result, sample_data, contour_cmap, dot_cmap, levels, xgrid, ygrid, 'Predictor1', 'Predictor2', base=0
you should avoid hardcoding values as much as possible

2025-01-13 16:58 UTC, erexer requested changes

2025-01-13 16:58 UTC, erexer commented on pyproject.toml
> +    "pytest-mock>=3.10",
These should be in the dev dependency section like [this](https://github.com/IMMM-SFA/msd_uncertainty_ebook/blob/dev/pyproject.toml#L52)

2025-01-13 16:58 UTC, erexer commented on msdbook/tests/test_utils.py
> +        ax, result, sample_data, contour_cmap, dot_cmap, levels, xgrid, ygrid, 'Predictor1', 'Predictor2', base=0
I should have been clearer here, for tests you want to have hardcoded values as inputs and outputs so that you can make sure the function is doing the right thing, but in general, if you're using the same value over and over, you should put it into a variable and use that variable. For example, you use `'Predictor1'` and `'Predictor2'` a lot so you should put those into variables.

2025-01-13 16:58 UTC, erexer commented on msdbook/tests/test_utils.py
> +    assert result.pvalues is not None
Is it possible to check that the parameters and values are correct?

2025-01-13 16:58 UTC, erexer commented on msdbook/tests/test_utils.py
> +    if not empty_df.empty:
is this checking for empty data or if it's not empty?

2025-01-20 19:09 UTC, Jaydon2005 commented on msdbook/tests/test_utils.py
> +    if not empty_df.empty:
It is checking if the data is not empty. The code inside the if block runs only if the DataFrame is not empty

2025-01-24 17:47 UTC, erexer commented on msdbook/tests/test_utils.py
> +    np.random.seed(0)  # For reproducibility
You should hard code the test values so that you can check the values of `result`

2025-02-07 15:36 UTC, erexer requested changes
Nice job, I've added some requested changes. Make sure you have pre-commit installed and it's running on any files you change. Mine is showing that `msdbook/utils.py` and `msdbook/tests/test_utils.py` need to be reformatted with pre-commit.

2025-02-07 15:36 UTC, erexer commented on msdbook/tests/test_utils.py
>      df = pd.DataFrame({
We want all of these to be hard coded values.

2025-02-07 18:02 UTC, Jaydon2005 commented on msdbook/tests/test_utils.py
> +EXPECTED_PARAMS = np.array([0.5, -0.3])  # Example expected coefficients (replace with real values)
I can just place it inside the test_fit_logit_with_expected_values function where it is used. This will make the code cleaner and more focused. I will take out the global initialization to make things clearer.

2025-02-07 18:55 UTC, Jaydon2005 commented on msdbook/tests/test_utils.py
> +EXPECTED_PVALUES = np.array([0.01, 0.04])  # Example expected p-values (replace with real values)
I'll remove this variable to avoid clutter since we want to check p-values

2025-02-13 16:13 UTC, erexer commented on msdbook/tests/test_utils.py
> +    assert np.allclose(result.params.values, EXPECTED_PARAMS, atol=1e-2)  # Tolerance for rounding errors
Can you check why we have to allow a tolerance and can't check exact values?

2025-02-24 18:08 UTC, erexer commented on msdbook/tests/test_utils.py
> +        'Interaction': []
You can change these to refer to the variables you set above

2025-02-24 18:09 UTC, erexer commented on msdbook/tests/test_utils.py
> +def test_empty_data():
can you rename this so that it's clear that it tests `fit_logit()`, something like `test_fit_logit_empty_data()`

2025-02-24 18:18 UTC, erexer commented on msdbook/tests/test_utils.py
> +    if not empty_df.empty:
Since we're testing with an empty df, this will never run and you can remove it

2025-02-24 18:19 UTC, erexer commented on msdbook/tests/test_utils.py
> +def test_invalid_predictors(sample_data):
can you rename this so that it's clear that it tests fit_logit(), something like test_fit_logit_invalid_predictors()`

2025-02-24 18:19 UTC, erexer commented on msdbook/tests/test_utils.py
> +def test_logit_with_interaction(sample_data):
I think we can remove this since we're already testing the interaction term above

2025-02-24 18:20 UTC, erexer commented on msdbook/tests/test_utils.py
> +# def test_fit_logit(sample_data, predictors, expected_params, min_coeff, max_coeff):
Can you clean up the commented code pls

2025-02-24 18:21 UTC, erexer commented on msdbook/tests/test_utils.py
> +def test_fit_logit_comprehensive(sample_data):
Can you add this to the parameterized tests (checking for `result.params.values`, `result.pvalues`)

2025-02-27 18:33 UTC, erexer commented on msdbook/tests/test_utils.py
>      EXPECTED_PARAMS = np.array([0.34060709, -0.26968773, 0.31551482, 0.45824332])  # Update with actual expected values
Is this comment out of date?

2025-02-27 18:34 UTC, erexer commented on msdbook/tests/test_utils.py
>      result = fit_logit(sample_data, ['Predictor1', 'Predictor2'])
There are variables for `Predictor1` and `Predictor2`

2025-02-27 18:37 UTC, erexer commented on msdbook/tests/test_utils.py
> +    assert np.all(np.abs(result.params) < 50)  # Coefficients should not exceed 50
Where does the number 50 come from? If there isn't a reason for this maximum we should get rid of this test.

2025-02-27 18:45 UTC, erexer commented on msdbook/tests/test_utils.py
>  def test_fit_logit(sample_data, df_resid, df_model, llf):
There should be 2 lines between function definitions

2025-02-27 18:49 UTC, erexer commented on msdbook/tests/test_utils.py
>  success = 'Success'
You should define these vars above `sample_data()` and use the vars in the function

2025-03-07 15:58 UTC, erexer commented on msdbook/tests/test_utils.py
> +    result = fit_logit(sample_data, [predictor1, predictor2])  # There are variables for predictor1 and predictor2
This comment is unnecessary

2025-03-07 15:59 UTC, erexer commented on msdbook/tests/test_utils.py
> +    assert np.all(np.abs(result.params) > 1e-5)  # Coefficients should not be too close to zero
Why should the coefficient not be too close to zero?

2025-03-07 16:00 UTC, erexer commented on msdbook/tests/test_utils.py
> +    assert np.allclose(result.params.values, EXPECTED_PARAMS, atol=0.1)  # Increased tolerance to 0.1
Why do we have a tolerance?

2025-03-10 16:34 UTC, Jaydon2005 commented on msdbook/tests/test_utils.py
> +    assert np.all(np.abs(result.params) > 1e-5)  # Coefficients should not be too close to zero
This check is valuable for confirming that the model is genuinely learning from the predictors and generating significant coefficients. By verifying that the coefficients are not excessively close to zero, it can ascertain that the predictors are making a meaningful contribution to the model's results. However the tests still pass without this assert and doesn't need to account for the significance of the coefficients.

2025-04-02 15:53 UTC, thurber commented
Looking good to me! I get a couple copies of the same warning when running the tests locally (can print my env if helpful), can you check if we can work around those or if they are expected?

> ======================================================================== warnings summary ========================================================================
> msdbook/tests/test_utils.py::test_fit_logit[sample_data1-0.0-2.0--2.4002923915238235e-06-expected_params1]
> msdbook/tests/test_utils.py::test_fit_logit[sample_data2-0.0-2.0--1.7925479970021486e-05-expected_params2]
>   /Users/thur961/im3/msd_uncertainty_ebook/venv/lib/python3.9/site-packages/statsmodels/base/model.py:595: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
>     warnings.warn('Inverting hessian failed, no bse or cov_params '
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> ================================================================= 7 passed, 2 warnings in 33.71s =================================================================

Em has a couple open questions above, can you respond to or resolve those?

2025-05-30 16:44 UTC, thurber commented on msdbook/tests/test_utils.py
>  def test_fit_logit(sample_data, df_resid, df_model, llf):
@Jaydon2005, can you double check you have the pre-commit running? i think that should format for PEP8 conventions

2025-05-30 16:48 UTC, thurber commented
@Jaydon2005, looking good, just a couple minor comments and can you confirm you've addressed Em's points above by resolving the conversations?

2025-05-30 20:14 UTC, Jaydon2005 commented on msdbook/tests/test_utils.py
>  def test_fit_logit(sample_data, df_resid, df_model, llf):
Yep, I have pre-commit set up and running. It uses ruff and black to format the code based on PEP8 rules. I just ran it on all files, and it automatically fixed a few formatting issues — so it’s working as expected.

2025-05-30 20:47 UTC, Jaydon2005 commented
> @Jaydon2005, looking good, just a couple minor comments and can you confirm you've addressed Em's points above by resolving the conversations?

Yes I can confirm

2025-05-30 21:05 UTC, thurber approved these changes

2025-06-06 17:59 UTC, merged